import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, LogOut, RefreshCw, Search } from 'lucide-react';
import { useNavigate } from 'react-router';

type Detail = { label: string; value: string };
type Memo = { id: string; nomorMemo: string; tanggalSubmit: string; supplierNama: string; outlets: string[]; jenisMemo: string; ringkasan: string; detail: Detail[]; periodeAwal?: string; periodeAkhir?: string };
type RekapRow = { kategori: string; jenis: string; qty: string; total: string };
type MediaRow = { kategori: string; detail: string; supplier: string; total: string; end: string };

const API = 'http://localhost:3001';
const names: Record<string, string> = { 'memo-program': 'Memo Program', 'pendapatan-lain': 'Memo Lain-lain', 'update-informasi': 'Update Informasi' };

const demoSections: Record<string, { rekap: RekapRow[]; detail: MediaRow[] }> = {
  'SIM-001': { rekap: [{ kategori: 'DISPLAY', jenis: 'N-GONDOLA', qty: '3', total: 'Rp 3.000.000,00' }, { kategori: 'DISPLAY', jenis: 'KLIP STRIP', qty: '2', total: 'Rp 2.000.000,00' }, { kategori: 'DISPLAY', jenis: 'WING-GONDOLA', qty: '5', total: 'Rp 5.000.000,00' }], detail: [{ kategori: 'DISPLAY', detail: 'N-GONDOLA FOOD & DRING', supplier: 'MAYORA', total: 'Rp 1.000.000,00', end: '30/12/2026' }, { kategori: 'DISPLAY', detail: 'N-GONDOLA FOOD & DRING', supplier: 'ULTRA', total: 'Rp 1.500.000,00', end: '31/12/2026' }, { kategori: 'DISPLAY', detail: 'N-GONDOLA HOME CARE', supplier: 'MOLTO', total: 'Rp 1.300.000,00', end: '01/01/2027' }, { kategori: 'DISPLAY', detail: 'N-GONDOLA HOME CARE', supplier: 'VIXAL', total: 'Rp 2.000.000,00', end: '02/01/2027' }] },
  'SIM-002': { rekap: [{ kategori: 'DISPLAY', jenis: 'WING-GONDOLA', qty: '2', total: 'Rp 8.500.000,00' }], detail: [{ kategori: 'DISPLAY', detail: 'WING GONDOLA MINUMAN', supplier: 'UNILEVER', total: 'Rp 4.250.000,00', end: '20/10/2026' }, { kategori: 'DISPLAY', detail: 'WING GONDOLA MINUMAN', supplier: 'UNILEVER', total: 'Rp 4.250.000,00', end: '20/10/2026' }] },
  'SIM-003': { rekap: [{ kategori: 'BRANDING', jenis: 'TVC/DIGITAL SIGNAGE', qty: '5', total: 'Rp 15.000.000,00' }], detail: [{ kategori: 'BRANDING', detail: 'DIGITAL SIGNAGE PINTU MASUK', supplier: 'MITRA DISTRIBUSI', total: 'Rp 5.000.000,00', end: '30/11/2026' }, { kategori: 'BRANDING', detail: 'DIGITAL SIGNAGE KASIR', supplier: 'MITRA DISTRIBUSI', total: 'Rp 5.000.000,00', end: '30/11/2026' }, { kategori: 'BRANDING', detail: 'DIGITAL SIGNAGE GONDOLA', supplier: 'MITRA DISTRIBUSI', total: 'Rp 5.000.000,00', end: '30/11/2026' }] },
  'SIM-004': { rekap: [{ kategori: 'DISPLAY', jenis: 'N-GONDOLA', qty: '3', total: 'Rp 10.000.000,00' }], detail: [{ kategori: 'DISPLAY', detail: 'N-GONDOLA FOOD & DRING', supplier: 'MAYORA', total: 'Rp 1.000.000,00', end: '30/12/2026' }, { kategori: 'DISPLAY', detail: 'N-GONDOLA FOOD & DRING', supplier: 'ULTRA', total: 'Rp 1.500.000,00', end: '31/12/2026' }, { kategori: 'DISPLAY', detail: 'N-GONDOLA HOME CARE', supplier: 'MOLTO', total: 'Rp 1.300.000,00', end: '01/01/2027' }, { kategori: 'DISPLAY', detail: 'N-GONDOLA HOME CARE', supplier: 'VIXAL', total: 'Rp 2.000.000,00', end: '02/01/2027' }] },
  'SIM-007': { rekap: [{ kategori: 'DISPLAY', jenis: 'WING-GONDOLA', qty: '2', total: 'Rp 8.500.000,00' }], detail: [{ kategori: 'DISPLAY', detail: 'WING GONDOLA', supplier: 'UNILEVER', total: 'Rp 4.250.000,00', end: '20/11/2026' }, { kategori: 'DISPLAY', detail: 'WING GONDOLA', supplier: 'UNILEVER', total: 'Rp 4.250.000,00', end: '20/11/2026' }] },
};

// Fallback simulasi agar laporan tetap dapat dilihat saat API belum dijalankan.
const demoMemos: Memo[] = [
  { id: 'SIM-001', nomorMemo: 'MEM-SIM-001', tanggalSubmit: '2026-09-10', supplierNama: 'PT. Indofood CBP Sukses Makmur', outlets: ['MK5'], jenisMemo: 'pendapatan-lain', ringkasan: 'Laporan Memo Lain-lain Display', detail: [], periodeAwal: '2026-01-01', periodeAkhir: '2026-04-30' },
  { id: 'SIM-002', nomorMemo: 'MEM-SIM-002', tanggalSubmit: '2026-09-15', supplierNama: 'PT. Unilever Indonesia Tbk', outlets: ['MK5', 'MK6'], jenisMemo: 'pendapatan-lain', ringkasan: 'Sewa Wing Gondola Promo Minuman', detail: [], periodeAwal: '2026-10-01', periodeAkhir: '2026-10-20' },
  { id: 'SIM-003', nomorMemo: 'MEM-SIM-003', tanggalSubmit: '2026-09-20', supplierNama: 'PT. Mitra Distribusi Nusantara', outlets: ['MK1', 'MK2', 'MK8'], jenisMemo: 'pendapatan-lain', ringkasan: 'Promosi Digital Signage Outlet', detail: [], periodeAwal: '2026-10-05', periodeAkhir: '2026-11-30' },
  { id: 'SIM-004', nomorMemo: 'MEM-SIM-004', tanggalSubmit: '2026-09-25', supplierNama: 'PT. Indofood CBP Sukses Makmur', outlets: ['MK1', 'MK3'], jenisMemo: 'pendapatan-lain', ringkasan: 'Event BLBMS Produk Indofood', detail: [], periodeAwal: '2026-10-01', periodeAkhir: '2026-10-25' },
  { id: 'SIM-006', nomorMemo: 'MEM-SIM-006', tanggalSubmit: '2026-10-01', supplierNama: 'PT. Indofood CBP Sukses Makmur', outlets: ['MK1', 'MK2', 'MK3', 'MK8'], jenisMemo: 'memo-program', ringkasan: 'Program Diskon Mie Instan Oktober', detail: [], periodeAwal: '2026-10-10', periodeAkhir: '2026-11-10' },
  { id: 'SIM-007', nomorMemo: 'MEM-SIM-007', tanggalSubmit: '2026-10-03', supplierNama: 'PT. Unilever Indonesia Tbk', outlets: ['MK5', 'MK6'], jenisMemo: 'pendapatan-lain', ringkasan: 'Sewa Wing Gondola Perpanjangan', detail: [], periodeAwal: '2026-11-01', periodeAkhir: '2026-11-20' },
];

const dateLabel = (value?: string) => { if (!value) return '-'; const [year, month, day] = value.split('-'); return year && month && day ? `${day}/${month}/${year}` : value; };
function getSections(memo: Memo) {
  if (demoSections[memo.id]) return demoSections[memo.id];
  const find = (pattern: RegExp) => memo.detail.find((item) => pattern.test(item.label))?.value || '-';
  return { rekap: [{ kategori: find(/kategori media/i), jenis: find(/jenis media/i), qty: find(/qty/i), total: find(/total|nilai/i) }], detail: [{ kategori: find(/kategori media/i), detail: find(/detail media/i), supplier: memo.supplierNama, total: find(/total|nilai/i), end: dateLabel(memo.periodeAkhir) }] };
}

function ReportSheet({ memo }: { memo: Memo }) {
  const sections = getSections(memo);
  return <section className="overflow-hidden rounded-xl border border-slate-300 bg-white shadow-sm"><div className="border-b border-slate-300 px-5 py-4"><h2 className="text-base font-bold uppercase tracking-wide text-slate-900">LAPORAN {names[memo.jenisMemo] || memo.jenisMemo}</h2><div className="mt-3 grid max-w-xl grid-cols-[100px_1fr] gap-y-1 text-sm"><span className="font-semibold">PERIODE</span><span>{dateLabel(memo.periodeAwal)} SD {dateLabel(memo.periodeAkhir)}</span><span className="font-semibold">MK</span><span>{memo.outlets.join(', ')}</span><span className="font-semibold">SUPPLIER</span><span>{memo.supplierNama}</span></div></div><div className="p-5"><h3 className="mb-3 text-sm font-bold uppercase tracking-wide text-slate-800">REKAP MEDIA</h3><div className="overflow-x-auto"><table className="w-full min-w-[650px] border-collapse text-sm"><thead><tr className="bg-slate-100 text-left text-[11px] uppercase tracking-wide text-slate-600"><th className="border border-slate-300 px-3 py-2">Kategori Media</th><th className="border border-slate-300 px-3 py-2">Jenis Media</th><th className="border border-slate-300 px-3 py-2 text-right">Qty</th><th className="border border-slate-300 px-3 py-2 text-right">Total</th></tr></thead><tbody>{sections.rekap.map((row, index) => <tr key={index}><td className="border border-slate-300 px-3 py-2">{row.kategori}</td><td className="border border-slate-300 px-3 py-2">{row.jenis}</td><td className="border border-slate-300 px-3 py-2 text-right">{row.qty}</td><td className="border border-slate-300 px-3 py-2 text-right">{row.total}</td></tr>)}</tbody></table></div><h3 className="mb-3 mt-8 text-sm font-bold uppercase tracking-wide text-slate-800">DETAIL MEDIA</h3><div className="overflow-x-auto"><table className="w-full min-w-[850px] border-collapse text-sm"><thead><tr className="bg-slate-100 text-left text-[11px] uppercase tracking-wide text-slate-600"><th className="border border-slate-300 px-3 py-2">Kategori Media</th><th className="border border-slate-300 px-3 py-2">Detail Media</th><th className="border border-slate-300 px-3 py-2">Supplier</th><th className="border border-slate-300 px-3 py-2 text-right">Total</th><th className="border border-slate-300 px-3 py-2">End Periode</th></tr></thead><tbody>{sections.detail.map((row, index) => <tr key={index}><td className="border border-slate-300 px-3 py-2">{row.kategori}</td><td className="border border-slate-300 px-3 py-2">{row.detail}</td><td className="border border-slate-300 px-3 py-2">{row.supplier}</td><td className="border border-slate-300 px-3 py-2 text-right">{row.total}</td><td className="border border-slate-300 px-3 py-2">{row.end}</td></tr>)}</tbody></table></div></div></section>;
}

export default function MemoReportSpreadsheet() {
  const nav = useNavigate(); const role = localStorage.getItem('bm-role'); const [rows, setRows] = useState<Memo[]>([]); const [search, setSearch] = useState(''); const [jenis, setJenis] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const load = () => fetch(`${API}/api/memo`).then((response) => { if (!response.ok) throw new Error('API memo tidak tersedia'); return response.json(); }).then((items) => setRows(Array.isArray(items) && items.length > 0 ? items : demoMemos)).catch(() => setRows(demoMemos));
  useEffect(() => { if (!['Akuntansi', 'Pembelian'].includes(role || '')) nav('/login'); else load(); }, [role]);
  const data = useMemo(() => rows.filter((memo) => (!search || JSON.stringify(memo).toLowerCase().includes(search.toLowerCase())) && (!jenis || memo.jenisMemo === jenis) && (!from || memo.tanggalSubmit >= from) && (!to || memo.tanggalSubmit <= to)), [rows, search, jenis, from, to]);
  const soon = data.filter((memo) => memo.periodeAkhir && ((new Date(`${memo.periodeAkhir}T00:00:00`).getTime() - Date.now()) / 86400000 <= 30));
  return <div className="flex h-full flex-col space-y-4 overflow-y-auto"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-widest text-amber-600">Laporan Internal</p><h1 className="text-xl font-extrabold text-slate-900">Laporan Memo</h1><p className="mt-1 text-sm text-slate-500">Laporan memo supplier untuk {role}.</p></div><div className="flex gap-2"><button onClick={load} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold"><RefreshCw className="h-3.5 w-3.5"/>Refresh</button><button onClick={() => { localStorage.removeItem('bm-role'); nav('/login'); }} className="inline-flex items-center gap-1.5 rounded-lg border border-red-200 bg-white px-3 py-2 text-xs font-bold text-red-600"><LogOut className="h-3.5 w-3.5"/>Keluar</button></div></div>{soon.length > 0 && <div className="rounded-xl border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-900"><AlertTriangle className="mr-2 inline h-4 w-4 animate-bounce"/><b>{soon.length} memo mendekati end periode.</b> Periksa kebutuhan perpanjangan sewa.</div>}<div className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid items-center gap-3 md:grid-cols-[1fr_220px_170px_170px]"><div className="flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2"><Search className="h-4 w-4 text-slate-400"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Cari supplier, memo, media..." className="w-full text-sm outline-none"/></div><select value={jenis} onChange={(event) => setJenis(event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="">Semua Jenis Memo</option>{Object.entries(names).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"/><input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"/></div></div><div className="grid grid-cols-1 gap-4">{data.map((memo) => <ReportSheet key={memo.id} memo={memo}/>)}{data.length === 0 && <div className="rounded-xl border border-slate-200 bg-white py-16 text-center text-sm text-slate-500">Tidak ada memo ditemukan.</div>}</div></div>;
}
